name: frontend_ci

on:
  push:
    branches: 
      - "main"
  pull_request:

jobs:
  frontend_lint_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - working-directory: frontend/app
        run: |
          npm install
          npm run lint
